In [2]:
# For: { x + 3y = 20
#      { 3x + 5y = 44
#
# A = [[1 3] 
#      [3 5]]
#
# B = [[20]
#      [44]]
#
# X = [[x]
#      [y]]
#
# X = inverse(A).B => inv() & dot()

# system format: {"variables": ["x","y"], "values": {0: [1,3], 1: [3,5]}, "totals": {0: 20, 1: 44}}

In [36]:
demo_system = {"variables": ["x","y"], "values": {0: [1,3], 1: [3,5]}, "totals": {0: 20, 1: 44}}

print(demo_system)
print(demo_system["variables"])
print(demo_system["variables"][0])
print(len(demo_system["variables"]))
print(len(demo_system["values"]))
X = demo_system["values"].values()
print(X)

{'variables': ['x', 'y'], 'values': {0: [1, 3], 1: [3, 5]}, 'totals': {0: 20, 1: 44}}
['x', 'y']
x
2
2
dict_values([[1, 3], [3, 5]])


In [18]:
import numpy as np
from numpy.linalg import inv, solve

In [45]:
def sys_solver(system):
    variables_amount = len(system["variables"])
    A_list = []
    B_list = []
    
    for value in range(len(system["values"])):
        A_list.append(system["values"][value])
        B_list.append(system["totals"][value])
    
    A_list = np.array(A_list)
    B_list = np.array(B_list)
    
    X_list = inv(A_list).dot(B_list)
    # X_list = solve(A_list,B_list)
    
    print("> Lista das variáveis:\n", A_list)
    print("> Lista dos resultados:\n", B_list)
    print("> Lista solução:\n", X_list)

In [46]:
demo_system = {"variables": ["x","y", "z"], "values": {0: [1, 3, 5], 1: [3, 5, 3], 2: [5, 7, 4]}, "totals": {0: 20, 1: 44, 2: 50}}

sys_solver(demo_system)

> Lista das variáveis:
 [[1 3 5]
 [3 5 3]
 [5 7 4]]
> Lista dos resultados:
 [20 44 50]
> Lista solução:
 [-16.  22.  -6.]
